services:

  # ── Astro SSR -sovellus ───────────────────────────────────────────────────
  astro:
    image: ghcr.io/djsnabu/nicecrm:latest
    restart: unless-stopped
    environment:
      HOST: "0.0.0.0"
      PORT: "4321"
    depends_on:
      - pocketbase

  # ── PocketBase ────────────────────────────────────────────────────────────
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    restart: unless-stopped
    volumes:
      - pb_data:/pb/pb_data

volumes:
  pb_data:
