services:

  # ── Astro SSR -sovellus ───────────────────────────────────────────────────
  astro:
    image: ghcr.io/djsnabu/nicecrm:latest
    container_name: nicecrm-astro
    restart: unless-stopped
    ports:
      - "4321:4321"
    environment:
      HOST: "0.0.0.0"
      PORT: "4321"
      PUBLIC_POCKETBASE_URL: "https://pb.niceevents.fi"
    depends_on:
      - pocketbase

  # ── PocketBase ────────────────────────────────────────────────────────────
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: nicecrm-pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/pb/pb_data

volumes:
  pb_data:
